version: '3'
services:
  local:
    build:
      context: .
    image: neural-networks-playground
    volumes:
      - .:/usr/src/app
    command: /bin/sh -c "while sleep 1000; do :; done"
    user: "1000:1000"
